project:
  type: website
  
website:
  site-url: https://johnmyers-phd.com
  title: "john myers, ph.d."
  favicon: img/fav.png
  draft-mode: unlinked
  google-analytics:
    tracking-id: "G-VWK3RHBGT2"
  
  navbar:
    title: false
    left:  
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Writings"
        href: writings.qmd
      - text: "Teaching"
        menu:
          - teaching/multi-calc-sp-26/multi-calc-sp-26.qmd
          - teaching/pde-sp-26/pde-sp-26.qmd
      - text: "Probabilistic Machine Learning"
        href: https://www.johnmyers-phd.com/book
        target: _blank
      - text: "SigAlg"
        href: https://www.johnmyers-phd.com/sigalg
        target: _blank
      - icon: github
        href: https://github.com/jmyers7/
        target: _blank
      - icon: bluesky
        href: https://bsky.app/profile/john-myers-phd.bsky.social
        target: _blank
      - icon: mastodon
        href: https://mathstodon.xyz/@jmyers7
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/john-myers-phd
        target: _blank
      - icon: envelope-open-fill
        href: mailto:jmmyers25@gmail.com
  
format:
  html:
    filters:
    - callouty-theorem
    theme: custom.scss
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&family=IBM+Plex+Mono:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap" rel="stylesheet">
    code-copy: true

highlight-style: custom.theme

callouty-theorem:
  thm:
    override-title: false
    callout:
      type: tip
      appearance: minimal
      collapse: false
      icon: false
  def:
    override-title: false
    callout:
      type: tip
      appearance: minimal
      collapse: false
      icon: false

execute: 
  warning: false
  message: false
  freeze: auto